apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: "restaurant"
            - name: PGPORT
              value: "5432"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
        - name: restaurant
          image: restaurant:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://db:5432/restaurant"
            - name: SPRING_LIQUIBASE_URL
              value: "jdbc:postgresql://db:5432/restaurant"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "1234"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "none"
          ports:
            - containerPort: 8080

---
# Сервис для доступа к приложению
apiVersion: v1
kind: Service
metadata:
  name: restaurant
spec:
  type: NodePort
  selector:
    app: restaurant
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080