java.runtime.version=11.0.16

# Database properties
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
#spring.jpa.show-sql=true
logging.level.root=DEBUG
# Liquibase properties
spring.liquibase.change-log=classpath:/liquibase/db.changelog-master.xml
spring.liquibase.user=postgres
spring.liquibase.password=1234

# Security properties
spring.security.user.name=user
spring.security.user.password=user

spring.main.allow-circular-references = true
server.ssl.enabled=false

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Spring Security OAuth2 Client configuration
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.client-id=restaurant_client
spring.security.oauth2.client.registration.keycloak.client-secret=XRYUmPtzuXcPq4KLrrr1BA1XJX1klwrK
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/keycloak

# OAuth2 Provider configuration - ? ?????? URI
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8082/realms/Restaurant_authorize
spring.security.oauth2.client.provider.keycloak.authorization-uri=http://localhost:8082/realms/Restaurant_authorize/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=http://keycloak:8080/realms/Restaurant_authorize/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://keycloak:8080/realms/Restaurant_authorize/protocol/openid-connect/certs
spring.security.oauth2.client.provider.keycloak.user-info-uri=http://keycloak:8080/realms/Restaurant_authorize/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

# OAuth2 Resource Server configuration (for JWT validation)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/Restaurant_authorize
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/realms/Restaurant_authorize/protocol/openid-connect/certs